### ISSUE TITLE
Builds out of date

### ISSUE THREAD

**Issue by isteiger** [noevidenz/multipaper-docker#18]
Hi! I am currently using your images to create a Kubernetes solution for Multipaper. Would you be able to restart the builds?

**Comment by isteiger** [comment]
I might be blind and only looked at the edge tag builds

**Comment by noevidenz** [comment]
Hi there, @isteiger!

The `edge` builds have been disabled because the build process was failing and I didn't have time to address it, however the `1.20` tag uses the latest release from the Multipaper API which appears to be based on the latest commit to their main branch anyway, meaning the edge branch is kind of redundant.

So if you're after the latest builds, your best bet is to use the `1.20` tag.
